# Generated by Django 4.1.5 on 2023-01-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
